[tool.poetry]
name = "ott-api-svc"
version = "1.0.3"
description = "OTT FastAPI Server"
authors = ["Akshay Kodali <akshay@ibeesolutions.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.95.2"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
motor = {extras = ["srv"], version = "^3.0.0"}
razorpay = "^1.4.2"
minio = "^7.1.7"
bcrypt = "^3.2.0"
PyJWT = "^2.3.0"
python-multipart = "^0.0.5"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}
google-auth = "^2.6.5"
cryptography = "^39.0.1"
firebase-admin = "^5.2.0"
boto3 = "^1.24.22"
redis = "^4.4.4"
pyOpenSSL = "^23.0.0"
paytmchecksum = "^1.7.0"
pytz = "^2022.4"
paytm-pg = "^1.1.1"
nanoid = "^2.0.0"
sendgrid = "^6.10.0"
httpx = "^0.27.2"
certifi = "^2024.8.30"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
